### ISSUE TITLE
Help with memory calculator

### ISSUE THREAD

**Issue by charyorde** [cloudfoundry/java-buildpack#239]
Hi,

I've configured the buildpack like htis:
```
---
jre:
  version: 1.8.0_60
  repository_root: "{default.repository.root}/openjdk/{platform}/{architecture}"
memory_calculator:
  version: 2.0.0_RELEASE
  repository_root: "{default.repository.root}/memory-calculator/{platform}/{architecture}"
  stack_threads: 
  memory_sizes:
    heap: 2048m..4096m
    metaspace: 2048m..4096m
    native: 
    permgen: 64m..
    stack: 
  memory_heuristics:
    heap: 75
    metaspace: 10
    native: 10
    permgen: 10
    stack: 5
  memory_initials:
    heap: 100%
    metaspace: 100%
    permgen: 100%
```

But I'm getting this:
```
-----> Downloading Open JDK Like Memory Calculator 2.0.0_RELEASE from https://download.run.pivotal.io/memory-calculator/trusty/x86_64/memory-calculator-2.0.0_RELEASE.tar.gz (found in cache)
[Buildpack]                      ERROR Compile failed with exception RuntimeError
       Cannot balance memory: Memory allocation failed for configuration: [heap:2G..4G metaspace:2G..4G], : Cannot allocate memory to '%!n(string=stack)' type
Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed
```
I don't understand what `Cannot allocate memory to '%!n(string=stack)' type` means.

In the manifest file for my app, I allocated 4G.

Appreciate your help.
