### ISSUE TITLE
JAVA_OPTS in manifest.yml FAIL without quotes

### ISSUE THREAD

**Issue by greenstevester** [cloudfoundry/java-buildpack#285]
my manifest.yml below ignores any -D option I set for JAVA_OPTS, unless I enclose it in quotes. Can someone tell me why this is?
```
---
# this is a cloudfoundry manifest, please see http://docs.run.pivotal.io/devguide/deploy-apps/manifest.html#find-manifest
# all applications use these settings and services
domain: cfapps.io
instances: 1
buildpack: https://github.com/cloudfoundry/java-buildpack
services:
- cleardb-msql-flightalert
applications:
- name: flightalert
host: flightalert
path: ../../target/flightalert-0.0.1-SNAPSHOT.war
env:
 JAVA_OPTS: -Dspring.main.show_banner=false
 SPRING_PROFILES_ACTIVE: cloud
```

**Comment by greenstevester** [comment]
@nebhale - thanks for the suggestion. The JAVA_OPTS: -Dspring.main.show_banner=false variable is happily read and set by cf and I am able to view them via the cloudfoundry console and I only find out when the app starts are there no JAVA_OPTS set - not very helpful at all. Also, nowhere in the cf documentation does it suggest that JAVA_OPTS variables need to be enclosed in quotes or at the very least a hint such as:  we recommend that you use http://www.yamllint.com to verify the manifest.yml before deploying. 

--- notifications@github.com wrote:

**Comment by nebhale** [comment]
@greenstevester I've just had a go a replicating your problem and can't.  For tests like this we use the [Java Test Applications](https://github.com/cloudfoundry/java-test-applications).  I've modified the [manifest of the `java-main-application`](https://github.com/cloudfoundry/java-test-applications/blob/master/java-main-application/manifest.yml) to look like:

```yaml
---
applications:
- name: java-main-application
  memory: 512M
  instances: 1
  path: build/libs/java-main-application-1.0.0.BUILD-SNAPSHOT.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
  stack: cflinuxfs2
  env:
    JAVA_OPTS: -Dspring.main.show_banner=false
```

Pushing the application with the CLI (version `6.16.1+924508c-2016-02-26`) results in a command line of:

```
App java-main-application was started using this command `CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.1_RELEASE -memorySizes=metaspace:64m.. -memoryWeights=heap:75,metaspace:10,native:10,stack:5 -memoryInitials=heap:100%,metaspace:100% -totMemory=$MEMORY_LIMIT) && JAVA_OPTS="-Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY -Dspring.main.show_banner=false" && SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/. org.springframework.boot.loader.JarLauncher`
```

as I'd expect.  When I `curl` the endpoint that exposes system properties with `curl -X "GET" "http://ben-java-main-application.cfapps.io/system-properties" | jq .`, I see:

```
{
  "PID": "14",
  "awt.toolkit": "sun.awt.X11.XToolkit",
  "catalina.base": "/home/vcap/tmp/tomcat.4639107425823626744.8080",
  "catalina.home": "/home/vcap/tmp/tomcat.4639107425823626744.8080",
  "catalina.useNaming": "false",
  "file.encoding": "UTF-8",
  "file.encoding.pkg": "sun.io",
  "file.separator": "/",
  "java.awt.graphicsenv": "sun.awt.X11GraphicsEnvironment",
  "java.awt.headless": "true",
  "java.awt.printerjob": "sun.print.PSPrinterJob",
  "java.class.path": "/home/vcap/app/.",
  "java.class.version": "52.0",
  "java.endorsed.dirs": "/home/vcap/app/.java-buildpack/open_jdk_jre/lib/endorsed",
  "java.ext.dirs": "/home/vcap/app/.java-buildpack/open_jdk_jre/lib/ext:/usr/java/packages/lib/ext",
  "java.home": "/home/vcap/app/.java-buildpack/open_jdk_jre",
  "java.io.tmpdir": "/home/vcap/tmp",
  "java.library.path": "/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib",
  "java.protocol.handler.pkgs": "null|org.springframework.boot.loader",
  "java.runtime.name": "OpenJDK Runtime Environment",
  "java.runtime.version": "1.8.0_73--vagrant_2016_02_08_16_47-b02",
  "java.specification.name": "Java Platform API Specification",
  "java.specification.vendor": "Oracle Corporation",
  "java.specification.version": "1.8",
  "java.vendor": "Oracle Corporation",
  "java.vendor.url": "http://java.oracle.com/",
  "java.vendor.url.bug": "http://bugreport.sun.com/bugreport/",
  "java.version": "1.8.0_73-",
  "java.vm.info": "mixed mode",
  "java.vm.name": "OpenJDK 64-Bit Server VM",
  "java.vm.specification.name": "Java Virtual Machine Specification",
  "java.vm.specification.vendor": "Oracle Corporation",
  "java.vm.specification.version": "1.8",
  "java.vm.vendor": "Oracle Corporation",
  "java.vm.version": "25.71-b02",
  "line.separator": "\n",
  "org.jboss.logging.provider": "slf4j",
  "os.arch": "amd64",
  "os.name": "Linux",
  "os.version": "3.19.0-49-generic",
  "path.separator": ":",
  "spring.beaninfo.ignore": "true",
  "spring.main.show_banner": "false",
  "sun.arch.data.model": "64",
  "sun.boot.class.path": "/home/vcap/app/.java-buildpack/open_jdk_jre/lib/resources.jar:/home/vcap/app/.java-buildpack/open_jdk_jre/lib/rt.jar:/home/vcap/app/.java-buildpack/open_jdk_jre/lib/sunrsasign.jar:/home/vcap/app/.java-buildpack/open_jdk_jre/lib/jsse.jar:/home/vcap/app/.java-buildpack/open_jdk_jre/lib/jce.jar:/home/vcap/app/.java-buildpack/open_jdk_jre/lib/charsets.jar:/home/vcap/app/.java-buildpack/open_jdk_jre/lib/jfr.jar:/home/vcap/app/.java-buildpack/open_jdk_jre/classes",
  "sun.boot.library.path": "/home/vcap/app/.java-buildpack/open_jdk_jre/lib/amd64",
  "sun.cpu.endian": "little",
  "sun.cpu.isalist": "",
  "sun.io.unicode.encoding": "UnicodeLittle",
  "sun.java.command": "org.springframework.boot.loader.JarLauncher",
  "sun.java.launcher": "SUN_STANDARD",
  "sun.jnu.encoding": "UTF-8",
  "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
  "sun.os.patch.level": "unknown",
  "user.country": "US",
  "user.dir": "/home/vcap/app",
  "user.home": "/home/vcap",
  "user.language": "en",
  "user.name": "vcap",
  "user.timezone": "Etc/UTC"
}
```

which has the specified `JAVA_OPTS` configuration.  How are you establishing that it isn't working?
