### ISSUE TITLE
JAVA_OPTS ignored 

### ISSUE THREAD

**Issue by MTyson** [cloudfoundry/java-buildpack#314]
The buildpack seems to be ignoring my JAVA_OPTS.

I am running a Java Ninja Framework app, as a standalone jar (which uses embedded Jetty).  If I run it locally:

`$ java -jar -Dninja.port=4444 new-app-1.0.0.jar`

The app starts up, and listens on port 4444: `o.e.jetty.server.ServerConnector - Started ServerConnector@c9d0d6{HTTP/1.1}{0.0.0.0:4444}`

However, this is not working when pushing to CF.

I have tried in the manifest:

```
---
applications:
- path: "./target/new-app-1.0.0.jar"
  memory: "500m"
  name: "foo-new-app"
  env:
    JAVA_OPTS: "-Dninja.port=$PORT"
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
```

As well as is `/config/java_opts.yml`:

```
# JAVA_OPTS configuration
---
from_environment: false
java_opts: -Dninja.port=$PORT
```

But the app always listens on 8080 anyway:

`OUT 03:25:29.979 [main] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@65ae6ba4{HTTP/1.1}{0.0.0.0:8080}`

And of course the app fails to start.
