### ISSUE TITLE
Unable to find cached file for https://java-buildpack.cloudfoundry.org/tomcat/tomcat-7.0.70.tar.gz

### ISSUE THREAD

**Issue by Omnipresent** [cloudfoundry/java-buildpack#337]
I'm trying to run a Grails 2.3.5 application on PCFDev (pcfdev-v0.20.0+PCF1.8.0-osx). I specified a version of Tomcat in my `manifest.yml`. However, while trying to push the app I get an error 

> Unable to find cached file for https://java-buildpack.cloudfoundry.org/tomcat/tomcat-7.0.70.tar.gz
> Failed to compile droplet
> -----> Downloading Tomcat Instance 7.0.70 from https://java-buildpack.cloudfoundry.org/tomcat/tomcat-7.0.70.tar.gz Exit status 223
> Staging failed: Exited with status 223

```
➜  cf-sample git:(all-buildconfig) ✗ cf push cf-sample -n cf-sample
Using manifest file /Users/bhaarat/code/grails/cf-sample/manifest.yml

Updating app cf-sample in org pcfdev-org / space pcfdev-space as user...
OK

Using route cf-sample.local.pcfdev.io
Uploading cf-sample...
Uploading app files from: /var/folders/c5/885z1_zn5z985rrq1bz7398r0000gn/T/unzipped-app323892694
Uploading 3.2M, 937 files
Done uploading
OK
Binding service mysql to app cf-sample in org pcfdev-org / space pcfdev-space as user...
OK

Starting app cf-sample in org pcfdev-org / space pcfdev-space as user...
Downloading java_buildpack...
Downloaded java_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (76.7M)
Downloading build artifacts cache...
Downloaded build artifacts cache (108B)
Staging...
-----> Java Buildpack Version: v3.8.1 (offline) | https://github.com/cloudfoundry/java-buildpack.git#29c79f2
-----> Downloading Open Jdk JRE 1.8.0_91-unlimited-crypto from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_91-unlimited-crypto.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (0.9s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
       Memory Settings: -Xms681574K -XX:MetaspaceSize=104857K -Xss349K -Xmx681574K -XX:MaxMetaspaceSize=104857K
-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
       Modifying /WEB-INF/web.xml for Auto Reconfiguration
[Buildpack]                      ERROR Compile failed with exception #<RuntimeError: Unable to find cached file for https://java-buildpack.cloudfoundry.org/tomcat/tomcat-7.0.70.tar.gz>
Unable to find cached file for https://java-buildpack.cloudfoundry.org/tomcat/tomcat-7.0.70.tar.gz
Failed to compile droplet
-----> Downloading Tomcat Instance 7.0.70 from https://java-buildpack.cloudfoundry.org/tomcat/tomcat-7.0.70.tar.gz Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed

TIP: use 'cf logs cf-sample --recent' for more information
```

My manifest.yml file looks like this:

```
---
applications:
  - name: cfsample
    memory: 1G
    instances: 1  
    path: target/cf-sample-0.1.war
    buildpack: java_buildpack
    services:
      - mysql
    env:
      JBP_CONFIG_TOMCAT: '{tomcat: { version: 7.0.+ }}'   
```

Additionally, what is a way to specify multiple environment variables in `manifest.yml`?

I tried the following which did not work. 

```
    env:
      JBP_CONFIG_OPEN_JDK_JRE '{jre: { version: 1.7.0_+ }}'
      JBP_CONFIG_TOMCAT: '{tomcat: { version: 7.0.+ }}'
```

**Comment by nebhale** [comment]
Offline buildpacks are only packaged with a single version of each dependency.  Since you're using `v3.8.1 (offline)`, your only option is [Tomcat 8.0.36](https://github.com/cloudfoundry/java-buildpack/releases/tag/v3.8.1).  To use a different version of Tomcat you'll need to use the online version of the buildpack (typically by specifying `https://github.com/cloudfoundry/java-buildpack.git#v3.9` as the buildpack) which will have access to the [complete repository](https://java-buildpack.cloudfoundry.org/tomcat/index.yml) of Tomcat versions.

**Comment by Omnipresent** [comment]
@nebhale Thank You. Could you also please suggest a way to specify multiple `env` in manifest.yml?

Doing below causes error: 

> Error reading manifest file:
> yaml: line 10: did not find expected key

```
---
applications:
  - name: cfsample
    memory: 1G
    instances: 1  
    path: target/cf-sample-0.1.war
    buildpack: java_buildpack
    services:
      - mysql
    env:
      JBP_CONFIG_OPEN_JDK_JRE '{jre: { version: 1.7.0_+ }}'
      JBP_CONFIG_TOMCAT: '{tomcat: { version: 7.0.+ }}'
```
