### ISSUE TITLE
Issue configuring Cloud Foundry Java Memory Parameters

### ISSUE THREAD

**Issue by Palani26** [cloudfoundry/java-buildpack#422]
Hi,

I am trying to reconfigure the metaspace size. By default, the memory calculator sets it to 64m

Start Command: `CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.2_RELEASE -memorySizes=metaspace:64m..,stack:228k..`

But with the new config changes, i dont see a configurable parameter - metaspace in `open_jdk_jre.yml` 
I only see stack_threads variable.

```
memory_calculator:
  version: 3.8.0_RELEASE
  repository_root: "{default.repository.root}/memory-calculator/{platform}/{architecture}"
  stack_threads: 300
```

In this case, how can we modify the metaspace size without forking and creating custom buildpack?
