### ISSUE TITLE
Add AWS Xray Tracing Support to Build pack

### ISSUE THREAD

**Issue by ygrene-austin** [cloudfoundry/java-buildpack#448]
We love cloud foundry, pcf and all things 12 factor. We have recently started using AWS X-Ray in our JVM based services. We would love to see this supported in the java build pack.
Currently these services are on elastic beanstalk and here is how we install them.
```
commands:
  700-download-daemon:
    command: curl https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-2.x.rpm -o /home/ec2-user/xray.rpm
    cwd: /tmp
  701-install-daemon:
    command: yum install -y /home/ec2-user/xray.rpm
    cwd: /tmp
    ignoreErrors: true
  702-check-daemon-installed:
    command: yum list installed xray
```
