### ISSUE TITLE
Feature request: stable branch or version tags on master

### ISSUE THREAD

**Issue by peterellisjones** [cloudfoundry/java-buildpack#806]
Hi Java Buildpack Team,

We use this repo to build an offline version of the Java buildpack. We'd like to only use commits that are part of a release but unfortunately there doesn't seem to be a way to do this with the way that commits to this repo are currently made. With the other buildpacks, version tags are associated with commits on the master branch so we can track commits that were part of a release with a Concourse git resource config which looks like this:

```
- name: php-buildpack-github
  type: git
  check_every: 30m
  source:
    uri: https://github.com/cloudfoundry/php-buildpack
    branch: master
    tag_filter: v* # Match any version tag
```

However this buildpack seems unique in that version tags do not appear on the master branch. For example the recent _v4.29.1_ release — https://github.com/cloudfoundry/java-buildpack/tree/v4.29.1 . The [commit](https://github.com/cloudfoundry/java-buildpack/commit/3dbe5826902a47a70b6084320ba75cb8b66aa157) which creates the release is not on master or any other branch. 

I can think of two possible solutions although I'm sure there are more:
* Create a 'stable' or 'release' branch which includes all commits that have been used to create actual releases. This way we can consume this branch to create our offline buildpacks
* Push the version commits to the master branch. This way we can track commits to version tags to create our offline buildpack

At the moment we are using the master branch which is not always stable.

kind regards,

Pete

**Comment by zoosm3** [comment]
I think you can include a version with `#` in your `uri` like this: 
``` https://github.com/cloudfoundry/java-buildpack.git#v4.29.1 ```

**Comment by nebhale** [comment]
This was a [long standing bug](https://github.com/concourse/git-resource/issues/74) (opened nearly 4 years ago) but was fixed in March of last year.  An appropriate configuration (that we use directly) looks like:

```
- name: java-buildpack-github
  type: git
  check_every: 30m
  source:
    uri: https://github.com/cloudfoundry/java-buildpack
    tag_filter: v*
```
