### ISSUE TITLE
Spring-Boot Access Denied for User

### ISSUE THREAD

**Issue by gangov** [cloudfoundry/java-buildpack#820]
Hey team, 

for the past few days, I've been struggling to find a solution to a connection problem:

I have a spring-boot application that runs in an app container, which I want to connect to MySQL service (FlyWay is also present); The error I'm getting  is Access denied for user 'username'@'ip_address' (using password: YES);

My manifest.yml looks like this:
```
applications:
  - name: app-name
    memory: 1G
    instances: 1
    buildpacks:
      - https://github.com/cloudfoundry/java-buildpack
    path: target/backend-1.0.1-SNAPSHOT.jar
    env:
      JBP_CONFIG_OPEN_JDK_JRE: '{jre: {version: 11.+}}'

```
and the application.yml file with the JDBC properties looks like that:
```
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${vcap.services.service-name.credentials.url:jdbc:mysql://service-name:3306/db-name?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${vcap.services.service-name.credentials.username:username}
    password: ${vcap.services.service-name.credentials.password:password}
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
  main:
    allow-bean-definition-overriding: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: ${vcap.services.service-name.credentials.username:username}
    password: ${vcap.services.service-name.credentials.password:password}
    url: ${vcap.services.service-name.credentials.url:jdbc:mysql://service-name:3306/db-name?createDatabaseIfNotExist=true&serverTimezone=UTC}
    skip-default-callbacks: true

```

Please, let me know what I'm missing or if any additional information is required from my end. 

Sincerely,
Kaloyan
