### ISSUE TITLE
Setting CF env variables from VCAP_SERVICES

### ISSUE THREAD

**Issue by metacubed** [cloudfoundry/java-buildpack#903]
Cloud Foundry injects some variables into deployed app environments. These variables can also be injected into the app manifest:

```yaml
applications:
- my-app:
    env:
      MY_APP_START_MSG: 'Starting app on port ${PORT}'
```

When the Java buildpack is used, it also processes the raw `VCAP_APPLICATION` and `VCAP_SERVICES` into new `vcap.application.*` and`vcap.services.<service-name>.*` variables.

Is there a way to inject those into the manifest? I'd like to do something like this, but it doesn't resolve correctly:

```yaml
applications:
- my-app:
    env:
      MY_VAR_1: 'Detected service binding ${vcap.services.my-svc.credentials.var-1}'
```
